import '@/styles/globalStyles.css'
import Head from 'next/head'
import {Roboto} from "@next/font/google";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700']
})

export default function App({ Component, pageProps }) {

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={roboto.className}>
        <Component {...pageProps} />
      </div>
    </>
  )
}
